### ISSUE TITLE
Getting errors with pga tour data scraper - need help please

### ISSUE THREAD

**Issue by GordonComstock1** [briceshun/PGA-Tour-Data#1]

**Comment by GordonComstock1** [comment]
Error in `mutate()`:
! Problem while computing `Name = ... %>% html_text()`.
Caused by error in `readBin()`:
! Failure when receiving data from the peer

Backtrace:
  1. ... %>% ...
 23. base::readBin(`<curl>`, "raw", 65536L)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `Name = ... %>% html_text()`.
Caused by error in `readBin()`:
! Failure when receiving data from the peer

**Comment by GordonComstock1** [comment]
Error in xml_attrs(values) : could not find function "xml_attrs"

**Comment by TommiKi** [comment]
You need to install few more packages.
install.packages("magrittr")
install.packages("xml2")
